---
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false
requirements:
    requiredStorage: 16
    requiredRam: 2.0
    check:
        - storage
        - ram
        - power
        - root
    required:
        - root
        - storage
        - ram
geoip:
    style: "none"
    url: "https://geoip.ubuntu.com/lookup"
    selector: "CountryCode"
