#!/bin/sh
set -e

lb config noauto \
  --mode ubuntu \
  --distribution noble \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --archive-areas "main restricted universe multiverse" \
  --debian-installer false \
  --linux-flavours generic \
  --memtest none \
  --bootappend-live "boot=live components quiet splash noeject username=winux hostname=winux locales=pl_PL.UTF-8 keyboard-layouts=pl"
