#!/bin/sh
set -e

lb config noauto \
  --mode ubuntu \
  --distribution noble \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --archive-areas "main restricted universe multiverse" \
  --debian-installer false \
  --linux-flavours generic \
  --memtest none \
  --apt-recommends false \
  --firmware-binary false \
  --firmware-chroot false \
  --iso-application "WinUX" \
  --iso-volume "WinUX" \
  --bootloader "grub-efi" \
  --bootappend-live "boot=live components quiet splash noeject username=winux hostname=winux locales=pl_PL.UTF-8 keyboard-layouts=pl"
